#Configurações da aplicação
#Thu May 14 21:19:41 GMT-03:00 2026
arcStepByStep.width=2.0
circle.diam=8
circle.width=1.0
creaseRef.color=255,0,0
creaseRef.width=1.0
creaseStepByStep.color=0,0,0
creaseStepByStep.width=2.0
creaseStepByStepFinal.color=0,255,0
fontSize=14
grid.color=0,153,0
grid.width=1.0
gridRef.color=255,0,255
gridRef.width=1.0
language=pt-BR
squareWidth=3.0
